### ISSUE TITLE
Do not override /etc/resolv.conf

### ISSUE THREAD

**Issue by jackgu1988** [jotyGill/openpyn-nordvpn#41] opened 2017-07-31 10:59 UTC
It would be useful to not override the DNS server of the host computer permanently. Some people might need a specific DNS server when not connected to VPN and they would lose it using openpyn-nordvpn.

It was mentioned in this discussion (https://github.com/jotyGill/openpyn-nordvpn/issues/30) that backing up and restoring on Ctrl-C might be dangerous -- I totally agree.

I found a workaround that I have not tested yet due to limited time here that could work: https://serverfault.com/questions/318563/how-to-push-my-own-dns-server-to-openvpn

On the .ovpn file if this is injected: `dhcp-option DNS <whatever>` theoretically it should work. So my suggestion is: before connecting copy `target-config.ovpn` to `temp-config.ovpn`, inject the necessary lines, and connect to the temp file.

**Comment by jotyGill** [comment] 2017-08-14 11:51
Hi Jack, nordvpn automatically pushes "dhcp-option DNS" so we don't need to (check the log paste). The problem is the OS still routes the DNS requests through whatever is in "resolvconf". I just confirmed that, DNS requests indeed go through the router (192.168.1.1 in my case) and are **not** encrypted. 
![dns in clear](https://user-images.githubusercontent.com/8462091/29270270-7b6f59a8-80e5-11e7-8353-331ae8508bff.png)

In case if you have to use the current DNS setting you can use the **--skip-dns-patch** option.
BTW this change to resolvconf is temperary. if you restart Network manager or if you reboot your machine, it should revert back to normal. So looking at this, I don't see a reason to backup and restore the file. what do you reckon?

"Mon Aug 14 20:47:01 2017 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,sndbuf 524288,rcvbuf 524288,**dhcp-option DNS 78.46.223.24,dhcp-option DNS 162.242.211.137**,route-gateway 10.7.7.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.7.7.33 255.255.255.0,peer-id 0,cipher AES-256-GCM'

**Comment by jotyGill** [comment] 2017-09-24 04:01
Any further thoughts on this issue?
if not, I would close it.

**Closed** 2017-09-27 01:41 UTC
