### ISSUE TITLE
Can this work with ipVanish?

### ISSUE THREAD

**Issue by blackhat840** [jotyGill/openpyn-nordvpn#88] opened 2018-01-16 03:06 UTC
Is it possible to use your tool with ipVanish instead of NordVPN?

**Comment by jotyGill** [comment] 2018-01-22 14:12
Not at this stage. would require quite a bit of work.

**Comment by jotyGill** [comment] 2018-02-17 03:44
I'll merge this to another issue.
duplicate of #91

**Closed by jotyGill** 2018-02-17 03:44 UTC
Labels: duplicate
